stages:
    - deploy

before_script:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy-to-webservers:
  stage: deploy
  only:
    - master
  script:
    - jekyll build
    - rsync -vrltgoDz --delete -e "ssh -p2222" ./_site/ systemli@www2.systemli.org:/var/www/www.systemli.org/www
    - rsync -vrltgoDz --delete -e "ssh -p22" ./_site/ systemli@www3.systemli.org:/var/www/www.systemli.org/www
    - rm -rf _site/
