name: Systemli - Your friendly tech collective
url: https://www.systemli.org
highlighter: pygments
source: ./src
include:
  - .well-known
  - .htaccess
  - assets/fingerprints.txt
  - assets/fingerprints.txt.asc

gems:
  - octopress-paginate
  - octopress-multilingual

pagination:
  limit: 5

lang: de
