name: Systemli - Your friendly tech collective
highlighter: pygments
source: ./src
include:
  - .well-known
  - .htaccess
  - assets/fingerprints.txt

gems:
  - octopress-paginate
  - octopress-multilingual

pagination:
  limit: 5

lang: de
