---

- hosts: all
  become: yes
  roles:
    - systemli.apache24
  tasks:
    - name: enable ssl
      command: a2ensite default-ssl.conf

    - name: reload apache
      service:
        name: apache2
        state: reloaded

    - name: install dependencies
      apt:
        pkg: 
          - ruby2.3
          - ruby2.3-dev
          - nodejs

    - name: install jekyll
      command: gem install jekyll:2.5.3 octopress:3.0.11 octopress-multilingual:1.2.0 octopress-paginate:1.2.0
      #gem:
      #  name: "{{ item.name }}"
      #  version: "{{ item.version }}"
      #with_items:
      #  - name: octopress-multilingual
      #    version: 1.2.0
      #  - name: octopress-paginate
      #    version: 1.2.0
      #  - name: octopress
      #    version: 3.0.11
      #  - name: jekyll
      #    version: 2.5.3

    - name: build site
      command: jekyll build --config "_config.yml,_dev.yml"
      args:
        chdir: /vagrant
